### ISSUE TITLE
Make align/demux work with custom fastq_list.csv not dependent on index/run folders

### ISSUE THREAD

**Issue by xroopnar** [ucladx/bcl-qc#6]
Right now the align and demux is meant only for use with the weekly novaseq runs. Add a separate script or option to simply pass a location of a fastq_list.csv, sample, and output location and run without any of those dependencies. this will be used for one off analyses or reanalyses separate from the normal weekly runs

**Comment by iatol1** [comment]
Fixed by 8a913ee83d3062c5a54c6e432e3c4087a7c84a31
